version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: uvicorn server.main:app --host 0.0.0.0
    volumes:
      - .:/api
    ports:
      - 8000:8000
  
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 8080:3000
